config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  post 'categories' => 'categories#create'
  get 'categories/new', as: 'new_category'
  get 'category/:id' => 'categories#show', as: 'category'

  get 'login' => 'login#new'
  post 'login' => 'login#create'
  delete 'logout' => 'login#destroy'
  # resource :session

  get 'register' => 'users#new'

  resources :posts do
    # POST '/posts/:post_id/comments' => 'comments#create'
    resources :comments, only: [:create]
  end

  resources :users

  concern :votable do
    post 'vote', on: :member
  end
  # POST '/comments/:id/vote'
  resources :comments, only: [:vote], concerns: :votable
  # POST '/posts/:id/vote'
  resources :posts, only: [:vote], concerns: :votable

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password

  validates :username, presence: true

  # users.yml
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # application_helper.rb
  def upvoted?(votable)
    (user_vote = votes.where(votable: votable).take) &&
      user_vote.voted == true
  end

  def downvoted?(votable)
    (user_vote = votes.where(votable: votable).take) &&
      user_vote.voted == false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:new, :create, :show]
  before_action :load_user, only: [:show, :edit, :update]
  before_action :authorize_user, only: [:edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "notice. registered and logged in"
    else
      flash[:error] = "error. try again"
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: "notice. user updated"
    else
      flash[:error] = "error. not updated"
      render action: 'edit'
    end
  end

  private

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def authorize_user
    unless user_authorized?
      flash[:error] = "error. not the current user"
      redirect_to user_url(@user)
    end
  end

  def user_authorized?
    current_user == @user
  end
end

app/views/users/edit.html.erb
<%= render 'shared/title', title: 'Edit Profile' %>

<%= form_for @user do |f| %>
  <div class="text-right"><%= f.submit class: "btn btn-default" %></div>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
<% end %>

<p class="text-right">
  <%= link_to "Back", user_path(@user), class: "btn btn-default" %>
</p>

app/views/users/new.html.erb
<%= render 'shared/title', title: 'Register' %>

<%= form_for :user, url: users_path do |f| %>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="text-right"><%= f.submit 'Register', class: "btn btn-default" %></div>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/title', title: @user.username %>

<p class="text-right">
  <% if correct_user?(@user) %>
    <%= link_to 'edit user', edit_user_path(@user), class: "btn btn-default" %>
  <% end %>
  <%= link_to 'back to all posts', posts_path, class: "btn btn-default" %>
</p>

<h4><%= pluralize(@user.comments.count, 'user comment') %></h4>
<div class="comment-blocks">
  <%= render @user.comments if @user.comments.any? %>
</div>

<h4><%= pluralize(@user.posts.count, 'user post') %></h4>
<div class="post-blocks">
  <%= render @user.posts if @user.posts.any? %>
</div>