config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  post 'categories' => 'categories#create'
  get 'categories/new', as: 'new_category'
  get 'category/:id' => 'categories#show', as: 'category'

  get 'login' => 'login#new'
  post 'login' => 'login#create'
  delete 'logout' => 'login#destroy'
  # resource :session

  get 'register' => 'users#new'

  resources :posts do
    # POST '/posts/:post_id/comments' => 'comments#create'
    resources :comments, only: [:create]
  end

  resources :users

  concern :votable do
    post 'vote', on: :member
  end
  # POST '/comments/:id/vote'
  resources :comments, only: [:vote], concerns: :votable
  # POST '/posts/:id/vote'
  resources :posts, only: [:vote], concerns: :votable

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :posts_categories, dependent: :destroy
  has_many :categories, through: :posts_categories
  belongs_to :user

  validates :title, presence: true

  include Votable

  before_validation :scrub_url
  validates :url, uniqueness: true

  def hashtag_words
    self.description.scan(/#\w+/)
    .map{|word| word.gsub!(/[[:punct:]]/, '')}
  end

  # to_param :title
  # http://api.rubyonrails.org/classes/ActiveRecord/Integration/ClassMethods.html#method-i-to_param
  def to_param
    if (param = title.to_s.squish.truncate(20, separator: /\s/, omission: nil).parameterize).present?
      param
    else
      super()
    end
  end

  def assign_categories
    id_array = self.category_ids
    self.hashtag_words.each do |word|
      word.downcase!
      id_array << Category.find_or_create_by(name: word).id
    end
    self.category_ids = id_array.uniq
  end

  def scrub_url
    return if url.nil?
    self.url = url.split('://').slice(1) if url.start_with?('http://', 'https://')
    self.url = url.split('.').slice(1..-1).join('.') if url.start_with?('www')
    self.url = url.chomp('/')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show, :vote]
  before_action :load_post, only: [:update, :edit, :show, :vote, :destroy]

  include Votables

  def destroy
    if user_log_in? && user_authorized?
      @post.destroy
      redirect_to posts_url, notice: "notice. post deleted"
    elsif user_log_in?
      flash[:error] = "error. not the user added this post"
      render template: 'posts/show'
    else
      flash[:error] = "error. log-in please"
      redirect_to login_url
    end
  end

  def index
    @posts = Post.order('updated_at desc').preload(:comments, :votes, :categories)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save && @post.assign_categories
      redirect_to post_url(@post), notice: "notice. post added"
    else
      flash[:error] = "error. not saved"
      render action: "new"
    end
  end

  def edit
    unless user_authorized? && user_log_in?
      flash[:error] = "error. not the user added this post"
      render template: 'posts/show'
    end
  end

  def update
    if user_log_in? && user_authorized?
      if @post.update(post_params) && @post.assign_categories
        redirect_to post_url(@post), notice: "notice. post updated"
      else
        flash[:error] = "error. not updated"
        render action: "edit"
      end
    elsif user_log_in?
      flash[:error] = "error. not the user added this post"
      render template: 'posts/show'
    else
      flash[:error] = "error. log-in please"
      redirect_to login_url
    end
  end

  def vote
    if user_log_in? && request.post?
      @post.voted_by(current_user, params[:voted])
    else
      flash[:error] = "error. login needed to vote"
    end
    redirect_to post_url(@post)
  end

  private

  def load_post
    @post = Post.all.select do |post|
      post.to_param == params[:id]
    end.first
    unless @post
      flash[:error] = "slug error"
      redirect_to root_url
    end
  end

  def post_params
    params.require(:post).permit(:url, :title, :description, category_ids: [])
  end

  def user_authorized?
    current_user == @post.user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def description_format text
    text.gsub!(/#\w+/) do |hashtag|
      if category = Category.find_by(name: hashtag[1..-1].downcase)
        link_to hashtag, category
      else
        hashtag
      end
    end
    simple_format text
  end
end

app/views/posts/_form.html.erb
<%= form_for @post, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="text-right"><%= f.submit class: "btn btn-default" %></div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <div class="checkbox">
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |box| %>
          <%= box.label class: "checkbox-inline" do %>
            <%= box.check_box %>
            <%= box.object.name %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="thumbnail">
  <div class="caption">
    <h3><%= link_to post.title, post, class: "my-btn" %></h3>
    <p>
      <span class="floats"><%= pluralize(post.net_votes, 'vote') %>,</span>
      <span class="floats"><%= pluralize(post.comments.size, 'comment') %></span>
    </p>
    <%= render post.categories %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/title', title: 'Edit Post' %>

<%= render 'form' %>

<p class="text-right">
  <%= link_to "Delete Post", @post, method: :delete, class: "btn btn-danger", data: { confirm: "click \"OK\" to delete" } %>
  <%= link_to "Back", post_path(@post), class: "btn btn-default" %>
</p>

app/views/posts/index.html.erb
<%= render 'shared/title', title: 'Welcome!' %>

<% if user_log_in? %>
  <p class="text-right">
    <%= link_to 'new category', new_category_path, class: "btn btn-default" %>
    <%= link_to 'new post', new_post_path, class: "btn btn-default" %>
  </p>
<% end %>

<h4><%= pluralize(@posts.count, 'post') %></h4>
<div class="post-blocks">
  <div class="thumbnail">
    <div class="caption">
      <%= content_tag(:span, "all #{Post.count}", class: "label label-all-primary") %>
      <%= render Category.all %>
    </div>
  </div>
  <%= render @posts if @posts.any? %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/title', title: 'New Post' %>

<%= render 'form' %>

<p class="text-right">
  <%= link_to "Back", posts_path, class: "btn btn-default" %>
</p>

app/views/posts/show.html.erb
<% provide(:post_slug, @post.to_param) %>

<p class="text-right">
  <% if @post && correct_user?(@post.user) %>
    <%= link_to 'edit post', edit_post_path(@post), class: "btn btn-default" %>
  <% end %>
  <%= link_to 'back to all posts', posts_path, class: "btn btn-default" %>
</p>

<div class="thumbnail">
  <div class="caption">

    <div class="panel panel-default text-center vote-panel">
      <div class="panel-body">
        <p><%= vote_up_arrow(@post) %></p>
        <p id="post_<%= @post.id %>_vote"><%= @post.net_votes %></p>
        <p><%= vote_down_arrow(@post) %></p>
      </div>
    </div>

    <%= render @post.categories %>

    <h2><%= @post.title %></h2>
    <p><%= link_to @post.url, external_url(@post.url), target: "_blank" %></p>
    <p><%= description_format @post.description %></p>

    <p class="text-right">
      <span class="floats">- added <%= time_ago_in_words @post.created_at %> ago,</span>
      <span class="floats">by <%= link_to @post.user.username, user_path(@post.user) %></span>
    </p>

  </div>
</div>

<h4><%= pluralize(@post.comments.count, 'post comment') %></h4>
<div class="comment-blocks">
  <%= render @post.comments if @post.comments.any? %>
</div>

<% if user_log_in? %>
<div class="well">
  <%= form_for [@post, @post.comments.new] do |f| %>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="text-right"><%= f.submit 'Add Comment', class: "btn btn-default" %></div>
  <% end %>
</div>
<% end %>

app/views/posts/vote.js.erb
// alert("hi");

$("#post_<%= @post.id %>_vote").html(function(){
  return "<%= @post.net_votes %>";
});