config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  post 'categories' => 'categories#create'
  get 'categories/new', as: 'new_category'
  get 'category/:id' => 'categories#show', as: 'category'

  get 'login' => 'login#new'
  post 'login' => 'login#create'
  delete 'logout' => 'login#destroy'
  # resource :session

  get 'register' => 'users#new'

  resources :posts do
    # POST '/posts/:post_id/comments' => 'comments#create'
    resources :comments, only: [:create]
  end

  resources :users

  concern :votable do
    post 'vote', on: :member
  end
  # POST '/comments/:id/vote'
  resources :comments, only: [:vote], concerns: :votable
  # POST '/posts/:id/vote'
  resources :posts, only: [:vote], concerns: :votable

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %> alert-dismissible" role="alert">
      <a class="close" data-dismiss="alert" aria-label=
      "Close"><span aria-hidden="true">&#215;</span></a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- <ul class="nav navbar-nav navbar-right">
  <li><a href="#">Link</a></li>
</ul> -->

<ul class="nav navbar-nav">
  <% if user_log_in? %>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Welcome, \"#{current_user.username}\"!", root_path, class: "navbar-brand" %>
    </div>

    <li>
      <%= link_to 'profile', current_user %>
    </li>
    <li>
      <%= link_to 'logout', logout_path, method: :delete %>
    </li>
  <% else %>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Resources!", root_path, class: "navbar-brand" %>
    </div>

    <li>
      <%= link_to 'register', register_path %>
    </li>
    <li>
      <%= link_to 'login', login_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <meta http-equiv="refresh" content="3"> -->
    <title><%= content_for?(:post_slug) ? yield(:post_slug) : "Share-Resources" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>

    <div role="navigation" class="navbar navbar-inverse">
      <div class="container-fluid">
        <%= render 'layouts/navigation' %>
      </div><!-- /.container-fluid -->
    </div>

    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div> <!--! end of .container -->

  </body>
</html>